spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshopdb
    username: myadmin
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher    

#http://localhost:8080/h2-console
#spring:
#  datasource:
#   url: jdbc:h2:mem:testdb
#   username: sa
#   password: 
#  jpa:
#   properties:
#    hibernate:
#    dialect: org.hibernate.dialect.H2Dialect
#   hibernate:
#    ddl-auto: create
#  h2:
#    console:
#      enabled: true